**❓ What is NumPy**

NumPy is a high performance numerical library that gives Python the power to work with large datasets efficiently. It provides fast, memory optimized arrays and mathematical tools that form the core of every machine learning workflow.

**⚙️ Why NumPy is Important in Machine Learning**

NumPy (Numerical Python) is the **foundation of all Machine Learning libraries in Python**.  
Almost every ML library — including Pandas, Scikit-Learn, TensorFlow, and PyTorch — is built on top of NumPy.

**🔍 Why It’s Essential**
- 🧮 **Efficient Computation:** Handles large numerical datasets faster than Python lists.
- 🧱 **Data Representation:** ML data (features & labels) are stored as matrices/tensors → NumPy arrays.
- ⚙️ **Vectorization:** Executes math operations on entire arrays without loops.
- 🔢 **Linear Algebra Support:** Used in gradient descent, covariance, matrix multiplication, etc.
- 🤝 **Integration:** Works seamlessly with Pandas, Matplotlib, Scikit-Learn, TensorFlow, and others.

> 💡 *If Python is the language of Machine Learning, NumPy is its mathematics engine.*

---


In [1]:
%pip install numpy==2.3.5

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 10.9 MB/s  0:00:00 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.5


**Compare list and numpy array**

In [7]:
import time
import numpy as np

n = 1000000

py_list = list(range(n))
np_array = np.array(py_list)

print(len(py_list))
print(len(np_array))

print(py_list[:5])
print(np_array[:5])


# Python list
t1 = time.time()
py_result = [x * 2 for x in py_list]   # multiply each element by 2
t2 = time.time()

# NumPy array (same operation)
t3 = time.time()
np_result = np_array * 2               # multiply each element by 2
t4 = time.time()

print("List time:", t2 - t1)
print("NumPy time:", t4 - t3)

1000000
1000000
[0, 1, 2, 3, 4]
[0 1 2 3 4]
List time: 0.014559030532836914
NumPy time: 0.0023021697998046875


In [9]:
a = []
for x in py_list:
    a.append(x * 2)
    
print(a[:5])

y =[x * 2 for x in py_list]
print(y[:5])

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


In [ ]:
b = np_array * 2
print(b[:5])

***Creating numpy arrays*

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [14]:
arr3 = np.array([[7, 8, 9], [10, 11, 12]]) # 2D array (matrix)
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array

print(arr3)
print(arr4)

[[ 7  8  9]
 [10 11 12]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
print("Shape of arr1:", arr1.shape)  # Output: (3,)
print("Shape of arr3:", arr3.shape)  # Output: (2, 3)
print("Shape of arr4:", arr4.shape)  # Output: (2, 2, 2)
print("Number of dimensions in arr1:", arr1.ndim)   # Output: 1
print("Number of dimensions in arr3:", arr3.ndim)   # Output: 2
print("Number of dimensions in arr4:", arr4.ndim)   # Output: 3
print("Data type of arr1:", arr1.dtype)  # Output: int64 (or int32 depending on the system)
print("Total number of elements in arr4:", arr4.size)   # Output: 8 (total number of elements in the array)

Shape of arr1: (3,)
Shape of arr3: (2, 3)
Shape of arr4: (2, 2, 2)
Number of dimensions in arr1: 1
Number of dimensions in arr3: 2
Number of dimensions in arr4: 3
Data type of arr1: int64
Total number of elements in arr4: 8


***creating special arrays**

In [20]:
zeros = np.zeros((2, 3))  # 2D array of zeros with shape (2, 3)
ones = np.ones((3, 4))    # 2D array of ones with shape (3, 4)
identity = np.eye(4)      # 4x4 identity matrix
random_array = np.random.rand(2, 5)  # 2D array of random numbers between 0 and 1 with shape (2, 5)
range_array = np.arange(0, 10, 2)  # 1D array of numbers from 0 to 10 with a step of 2
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Random Array:\n", random_array)
print("Range Array:\n", range_array)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Array:
 [[0.52674093 0.49071548 0.1251221  0.63329873 0.64829237]
 [0.90370774 0.6118108  0.0350931  0.9393787  0.18183733]]
Range Array:
 [0 2 4 6 8]


**indexing  & slicing**

In [22]:
arr = np.array([[1, 2, 3]
                , [4, 5, 6]
                , [7, 8, 9]])
print("First row:", arr[0])      # First row
print("Second row:", arr[1])      # Second row
print("Third row:", arr[2])      # Third row
print("First row, first column:", arr[0, 0])   # First row, first column
print("Second row, third column:", arr[1, 2])   # Second row, third column
print("All rows, first column:", arr[:, 0])   # All rows, first column
print("All rows, second column:", arr[:, 1])   # All rows, second column
print("All rows, third column:", arr[:, 2])   # All rows, third column

First row: [1 2 3]
Second row: [4 5 6]
Third row: [7 8 9]
First row, first column: 1
Second row, third column: 6
All rows, first column: [1 4 7]
All rows, second column: [2 5 8]
All rows, third column: [3 6 9]


***array operations**

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Element-wise addition
print("Element-wise addition:", c)     # Output: [5 7 9]
print("Element-wise multiplication:", a * b)  # Output: [4 10 18]
print("Element-wise division:", a / b)  # Output: [0.25 0.4 0.5]
print("dot product:", np.dot(a, b))  # Output: 32 (1*4 + 2*5 + 3*6)
print("cross product:", np.cross(a, b))  # Output: [-3 6 -3] (only for 3D vectors)

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Element-wise division: [0.25 0.4  0.5 ]
dot product: 32
cross product: [-3  6 -3]


**reshaping**

In [28]:
arr3 = np.arange(1, 10)
reshaped = arr3.reshape((3, 3))
flattened = reshaped.flatten()
print("Original array:", arr3)
print("Reshaped array:\n", reshaped)
print("Flattened array:", flattened)

Original array: [1 2 3 4 5 6 7 8 9]
Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array: [1 2 3 4 5 6 7 8 9]
